### ISSUE TITLE
Random Errors?

### ISSUE THREAD

**Issue by GameKnighted** [games647/ScoreboardStats#111]
When i downloaded the plugin, it didnt work. I downloaded a different version and it worked. Then when i restarted my server it gave an error.

Here is the error:

[09:13:14 ERROR]: Could not load 'plugins\ScoreboardStats (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_101]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_101]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_101]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_101]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 5 more

**Comment by games647** [comment]
Corrupt file. Try to redownload and deploy it.
