### ISSUE TITLE
Bug on /sidebar reload

### ISSUE THREAD

**Issue by Creatif** [games647/ScoreboardStats#123]
Hello,

me again :p
(I compile the current github version, so it's just for your information, not a big deal)

Concerning ASkyBlock variables:
Could you add a variable to count how many times all challenges were made ?
In ASkyBlock, challenges could be made severals times ;)
like %challenge_total%

Concerning reload:

```
[23:07:54] [Server thread/INFO]: iCrea issued server command: /sidebar reload
[23:07:54] [Server thread/INFO]: [ScoreboardStats] Path not fond disabled-worlds-whitelist
[23:07:54] [Server thread/INFO]: [ScoreboardStats] Registered replacers: [PlayerPingVariable, BungeeCordVariables, BukkitGlobalVariables, GeneralVariables, BukkitVariables, VaultVariables, ASkyBlockVariables]
[23:07:54] [Server thread/INFO]: SubClassFactory parent ClassLoader [com.github.games647.scoreboardstats.ReloadFixLoader]
[23:07:54] [Server thread/INFO]: Entities enhanced[0] subclassed[1]
[23:07:54] [Server thread/INFO]: runScript
[23:07:54] [Server thread/INFO]: executing 1 of 1 create table IF NOT EXISTS player_stats ( id                        integer prim...
[23:07:54] [Server thread/INFO]: ... end of script
[23:07:54] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
java.lang.NullPointerException: The bean is null?
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:304) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1820) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1806) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$3(Database.java:227) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

**Comment by games647** [comment]
Issue with bukkit's class loading. I cannot fix it.
