### ISSUE TITLE
ERROR executing DML bindLog[] error[[SQLITE_CONSTRAINT]

### ISSUE THREAD

**Issue by andris155** [games647/ScoreboardStats#128]
version: 0.9.11
```
[15:01:22] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[[SQLITE_CONSTRAINT]  Abort due to constraint violation (PRIMARY KEY must be unique)]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1820) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1806) ~[patched_1.10.2.jar:git-Paper-864]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$2(Database.java:227) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (PRIMARY KEY must be unique)
	at org.sqlite.DB.newSQLException(DB.java:383) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.DB.newSQLException(DB.java:387) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.DB.execute(DB.java:342) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.DB.executeUpdate(DB.java:363) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:164) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:74) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:158) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105) ~[patched_1.10.2.jar:git-Paper-864]
	... 19 more
[15:03:53] [Server thread/INFO]: MissQueen fell out of the world
[15:06:16] [Server thread/INFO]: MissQueen fell out of the world
[15:06:22] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[statement is not executing]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1820) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1806) ~[patched_1.10.2.jar:git-Paper-864]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$2(Database.java:227) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.sql.SQLException: statement is not executing
	at org.sqlite.Stmt.checkOpen(Stmt.java:49) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.PrepStmt.batch(PrepStmt.java:170) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.PrepStmt.setInt(PrepStmt.java:197) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.setInt(ExtendedPreparedStatement.java:297) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.DataBind.setInt(DataBind.java:86) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:45) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:35) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.bind(BeanProperty.java:663) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bindInternal(DmlHandler.java:264) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bind(DmlHandler.java:223) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:102) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:91) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.InsertMeta.bind(InsertMeta.java:156) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.bind(InsertHandler.java:133) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:98) ~[patched_1.10.2.jar:git-Paper-864]
	... 19 more
[15:09:21] [Server thread/INFO]: CommandBlock at -1,450,78,-99 issued server command: /tp MissQueen -1485 80 -104
[15:09:45] [Server thread/INFO]: MissQueen issued server command: /spawn
[15:11:22] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[statement is not executing]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1820) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1806) ~[patched_1.10.2.jar:git-Paper-864]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$2(Database.java:227) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.sql.SQLException: statement is not executing
	at org.sqlite.Stmt.checkOpen(Stmt.java:49) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.PrepStmt.batch(PrepStmt.java:170) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.PrepStmt.setInt(PrepStmt.java:197) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.setInt(ExtendedPreparedStatement.java:297) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.DataBind.setInt(DataBind.java:86) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:45) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:35) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.bind(BeanProperty.java:663) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bindInternal(DmlHandler.java:264) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bind(DmlHandler.java:223) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:102) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:91) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.InsertMeta.bind(InsertMeta.java:156) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.bind(InsertHandler.java:133) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:98) ~[patched_1.10.2.jar:git-Paper-864]
	... 19 more
[15:11:38] [Server thread/INFO]: MissQueen issued server command: /spawn
[15:11:39] [Server thread/INFO]: MissQueen fell out of the world
[15:12:54] [Server thread/INFO]: MissQueen fell from a high place
[15:16:22] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[statement is not executing]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1820) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1806) ~[patched_1.10.2.jar:git-Paper-864]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$2(Database.java:227) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.sql.SQLException: statement is not executing
	at org.sqlite.Stmt.checkOpen(Stmt.java:49) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.PrepStmt.batch(PrepStmt.java:170) ~[patched_1.10.2.jar:git-Paper-864]
	at org.sqlite.PrepStmt.setInt(PrepStmt.java:197) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.setInt(ExtendedPreparedStatement.java:297) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.DataBind.setInt(DataBind.java:86) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:45) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:35) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.bind(BeanProperty.java:663) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bindInternal(DmlHandler.java:264) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bind(DmlHandler.java:223) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:102) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:91) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.InsertMeta.bind(InsertMeta.java:156) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.bind(InsertHandler.java:133) ~[patched_1.10.2.jar:git-Paper-864]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:98) ~[patched_1.10.2.jar:git-Paper-864]
	... 19 more
```

**Comment by games647** [comment]
Duplicate #127
