### ISSUE TITLE
Cannot register replacer

### ISSUE THREAD

**Issue by SlimeDog** [games647/ScoreboardStats#131]
Spigot 1.10.2 latest pull, all plugins latest pulls, ProtocolLib 4.1.0, ScoreboardStats 0.9.12. On startup, SS produced the following error log. Standalone Spigot server, i.e., not running BungeeCord.

[14:33:47] [Server thread/INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.9.12
[14:33:47] [Server thread/WARN]: [ScoreboardStats] Cannot register replacer
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_102]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_102]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_102]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.createInstance(ReplaceManager.java:372) ~[ScoreboardStats-0.9.12.jar:?]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.registerDefault(ReplaceManager.java:302) [ScoreboardStats-0.9.12.jar:?]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.addDefaultReplacers(ReplaceManager.java:358) [ScoreboardStats-0.9.12.jar:?]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.<init>(ReplaceManager.java:86) [ScoreboardStats-0.9.12.jar:?]
        at com.github.games647.scoreboardstats.SbManager.<init>(SbManager.java:27) [ScoreboardStats-0.9.12.jar:?]
        at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.<init>(BukkitScoreboardManager.java:37) [ScoreboardStats-0.9.12.jar:?]
        at com.github.games647.scoreboardstats.ScoreboardStats.onEnable(ScoreboardStats.java:136) [ScoreboardStats-0.9.12.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalArgumentException: Plugin cannot be null
        at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:176) ~[spigot-1.10.2.jar-2016-09-19-1004:git-Spigot-570526c-c1b529e]
        at com.github.games647.scoreboardstats.variables.defaults.BungeeCordVariables.<init>(BungeeCordVariables.java:32) ~[?:?]
        ... 22 more
[14:33:47] [Server thread/INFO]: [ScoreboardStats] Registered replacers: [BukkitGlobalVariables, PlayerPingVariable, GeneralVariables, BukkitVariables, VaultVariables, ASkyBlockVariables]

./plugins/ScoreboardStats/config.yml, sans comments:

compatibilityMode: false

disabled-worlds-whitelist: false

disabled-worlds:

Scoreboard:
  Title: ''
  Update-delay: 2
  Items:
    '&0tps': '%tps%'
    '&0ping': '%ping%'
    '&0players': '%online%'

enable-pvpstats: false

Temp-Scoreboard-enabled: false

Temp-Scoreboard:
  Title: '&a&lTop Kills'
  Type: '%kills%'
  Color: '&9'
  Items: 5
  Intervall-show: 300
  Intervall-disappear: 300

pluginUpdate: false

**Comment by SlimeDog** [comment]
And every minute thereafter:

[15:03:49 ERROR]: [ScoreboardStats] null
java.lang.NullPointerException
        at com.github.games647.scoreboardstats.pvpstats.Database.lambda$null$2(Database.java:233) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_102]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_102]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_102]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_102]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_102]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_102]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_102]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_102]
        at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$3(Database.java:233) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_102]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]

**Comment by SlimeDog** [comment]
Verified fix. Thanks.
