### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JugadorON** [games647/ScoreboardStats#132]
Craftbukkit 1.10.2

ScoreboardStats v0.9.12

Error:

[01:33:32] [Server thread/INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.9.12 [01:33:32] [Server thread/WARN]: [ScoreboardStats] Cannot register replacer java.lang.reflect.InvocationTargetException at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_101] at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_101] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_101] at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_101] at com.github.games647.scoreboardstats.variables.ReplaceManager.createInstance(ReplaceManager.java:372) [ScoreboardStats.jar:?] at com.github.games647.scoreboardstats.variables.ReplaceManager.registerDefault(ReplaceManager.java:302) [ScoreboardStats.jar:?] at com.github.games647.scoreboardstats.variables.ReplaceManager.addDefaultReplacers(ReplaceManager.java:358) [ScoreboardStats.jar:?] at com.github.games647.scoreboardstats.variables.ReplaceManager.<init>(ReplaceManager.java:86) [ScoreboardStats.jar:?] at com.github.games647.scoreboardstats.SbManager.<init>(SbManager.java:27) [ScoreboardStats.jar:?] at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.<init>(BukkitScoreboardManager.java:37) [ScoreboardStats.jar:?] at com.github.games647.scoreboardstats.ScoreboardStats.onEnable(ScoreboardStats.java:136) [ScoreboardStats.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [CraftBukkit.jar:git-Bukkit-c1b529e] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [CraftBukkit.jar:git-Bukkit-c1b529e] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [CraftBukkit.jar:git-Bukkit-c1b529e] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:358) [CraftBukkit.jar:git-Bukkit-c1b529e] at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:320) [CraftBukkit.jar:git-Bukkit-c1b529e] at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:404) [CraftBukkit.jar:git-Bukkit-c1b529e] at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:369) [CraftBukkit.jar:git-Bukkit-c1b529e] at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:324) [CraftBukkit.jar:git-Bukkit-c1b529e] at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:243) [CraftBukkit.jar:git-Bukkit-c1b529e] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:514) [CraftBukkit.jar:git-Bukkit-c1b529e] at java.lang.Thread.run(Unknown Source) [?:1.8.0_101] Caused by: java.lang.IllegalArgumentException: Plugin cannot be null at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:176) [CraftBukkit.jar:git-Bukkit-c1b529e] at com.github.games647.scoreboardstats.variables.defaults.BungeeCordVariables.<init>(BungeeCordVariables.java:32) [?:?] ... 22 more [01:33:32] [Server thread/INFO]: [ScoreboardStats] Registered replacers: [PlayerPingVariable, BukkitGlobalVariables, GeneralVariables, BukkitVariables, VaultVariables]

**Comment by games647** [comment]
Duplicate #131
