### ISSUE TITLE
Players kicked reloading scoreboard with UTF-8 characters

### ISSUE THREAD

**Issue by Eufranio** [games647/ScoreboardStats#138]
When I use UTF-8 characters in the scoreboard, and reload with /sb reload, some players are kicked. I'm using latetest (0.9.14) build from bukkit. There is no errors, they're kicked just by "the server you were was down, you were moved to the default/fallback server".

I'm using a Thermos B58 1.7.10 server, and BungeeCord from HexagonMC.

**Comment by games647** [comment]
Then I need your bungee log

**Comment by Eufranio** [comment]
Okay:

```
16:16:37 [SEVERE] [_Maah1315_] <-> DownstreamBridge <-> [MagiTech] - encountered exception
java.lang.IllegalArgumentException: Objective Stats already exists in this scoreboard
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at net.md_5.bungee.api.score.Scoreboard.addObjective(Scoreboard.java:55)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:125)
    at net.md_5.bungee.protocol.packet.ScoreboardObjective.handle(ScoreboardObjective.java:62)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:972)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:386)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by games647** [comment]
Do you use compatible mode?

**Comment by Eufranio** [comment]
Yes

**Comment by Eufranio** [comment]
This bug isn't fixed yet... Using ScoreboardStats v0.9.15

**Comment by games647** [comment]
What's your plugin list?

**Comment by games647** [comment]
BungeeCord and Spigot

**Comment by Eufranio** [comment]
Spigot: Plugins (40): aUCVault, Itemizer, WorldEdit, OpenInv, Offline_Teleporter, BetterChunkLoader, ClearLag, AutoMessage, PlugMan, VipZeroFIX, ConsoleSpamFix, ProtocolLib, WorldGuard, MagiUtils, MultiWorld, ChatReaction, eZProtector, AsyncWorldEdit, PermissionsEx, Magi-GUI, Vault, MyCommand, BungeeTabListPlus, BetterAlias, ItemRestrict, FastLogin, Essentials, ScoreboardStats, Trading, RandomTP, HolographicDisplays, VipZero, Citizens, Legendchat, TagsGUI-2.0, ChestCommands, DiscordSRV, EssentialsSpawn, AuthMe, AuthMeBridge

**Comment by Eufranio** [comment]
Bungee: AdvancedBan, AntiBotAttack, BungeeAliases, Bungee AuthMeBridge, BungeePluginManager, BungeePerms, BungeeTabListPlus, FastLogin, ServerListPlus, SkinsRestorer and MoveMeNow.
