### ISSUE TITLE
[Server thread/ERROR]: [ScoreboardStats] null

### ISSUE THREAD

**Issue by Someone-NEW** [games647/ScoreboardStats#140]
[11:50:54] [Server thread/INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.9.14
[11:50:54] [Server thread/INFO]: [ScoreboardStats] Path not fond disabled-worlds-whitelist
[11:50:54] [Server thread/INFO]: [ScoreboardStats] Registered replacers: [BukkitGlobalVariables, BungeeCordVariables, PlayerPingVariable, GeneralVariables, BukkitVariables, VaultVariables]
[11:50:54] [Server thread/ERROR]: ebean.properties not found
[11:50:54] [Server thread/ERROR]: [ScoreboardStats] null
java.lang.NoSuchFieldException: annotations
	at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_66]
	at com.github.games647.scoreboardstats.pvpstats.DatabaseConfiguration.setTablePrefix(DatabaseConfiguration.java:191) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.pvpstats.DatabaseConfiguration.getSqlConfig(DatabaseConfiguration.java:121) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.pvpstats.DatabaseConfiguration.loadConfiguration(DatabaseConfiguration.java:75) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.setupDatabase(Database.java:194) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.ScoreboardStats.onEnable(ScoreboardStats.java:141) [ScoreboardStats.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
[11:50:54] [Server thread/INFO]: Using [com.github.games647.scoreboardstats.pvpstats.PathReader] to read the searchable class path
[11:50:54] [Server thread/INFO]: DataSourcePool [ScoreboardStats] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[11:50:54] [Server thread/INFO]: SubClassFactory parent ClassLoader [com.github.games647.scoreboardstats.ReloadFixLoader]
[11:50:58] [Server thread/INFO]: Entities enhanced[0] subclassed[1]
[11:50:58] [Server thread/INFO]: runScript
[11:50:58] [Server thread/INFO]: executing 1 of 1 create table IF NOT EXISTS player_stats ( id                        integer prim...
[11:50:58] [Server thread/INFO]: ... end of script

**Comment by Someone-NEW** [comment]
What should be here wrong? is here any solution for this?

**Comment by games647** [comment]
Duplicate #139
