### ISSUE TITLE
Error ebean.properties not found or annotations

### ISSUE THREAD

**Issue by MrRaik** [games647/ScoreboardStats#145]
[19:37:58] [Server thread/INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.9.14
[19:37:58] [Server thread/INFO]: [ScoreboardStats] Registered replacers: [PlayerPingVariable, BungeeCordVariables, BukkitGlobalVariables, GeneralVariables, BukkitVariables, VaultVariables]
[19:37:58] [Server thread/ERROR]: ebean.properties not found
[19:37:58] [Server thread/ERROR]: [ScoreboardStats] null
java.lang.NoSuchFieldException: annotations
at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_92]
at com.github.games647.scoreboardstats.pvpstats.DatabaseConfiguration.setTablePrefix(DatabaseConfiguration.java:191) [ScoreboardStats.jar:?]
at com.github.games647.scoreboardstats.pvpstats.DatabaseConfiguration.getSqlConfig(DatabaseConfiguration.java:121) [ScoreboardStats.jar:?]
at com.github.games647.scoreboardstats.pvpstats.DatabaseConfiguration.loadConfiguration(DatabaseConfiguration.java:75) [ScoreboardStats.jar:?]
at com.github.games647.scoreboardstats.pvpstats.Database.setupDatabase(Database.java:194) [ScoreboardStats.jar:?]
at com.github.games647.scoreboardstats.ScoreboardStats.onEnable(ScoreboardStats.java:141) [ScoreboardStats.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:416) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:381) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:336) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:270) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:539) [spigotmc-1.10-R0.1.jar:git-Spigot-c3e4052-1953f52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
[19:37:58] [Server thread/INFO]: Using [com.github.games647.scoreboardstats.pvpstats.PathReader] to read the searchable class path
[19:37:59] [Server thread/INFO]: DataSourcePool [ScoreboardStats] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[19:37:59] [Server thread/INFO]: SubClassFactory parent ClassLoader [com.github.games647.scoreboardstats.ReloadFixLoader]
[19:37:59] [Server thread/INFO]: Entities enhanced[0] subclassed[1]
[19:37:59] [Server thread/INFO]: runScript
[19:37:59] [Server thread/INFO]: executing 1 of 1 create table IF NOT EXISTS player_stats ( id integer prim...
[19:37:59] [Server thread/INFO]: ... end of script

**Comment by games647** [comment]
Duplicate #143

**Comment by MrRaik** [comment]
Wath ??
