### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by dexter132** [games647/ScoreboardStats#146]
When start server. I see error:
```
23.10 02:34:57 [Server] ERROR null
23.10 02:34:57 [Server] INFO java.lang.NoSuchFieldException: annotations
23.10 02:34:57 [Server] INFO at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_92]
23.10 02:34:57 [Server] INFO at com.github.games647.scoreboardstats.pvpstats.DatabaseConfiguration.setTablePrefix(DatabaseConfiguration.java:191) [ScoreboardStats.jar:?]
23.10 02:34:57 [Server] INFO at com.github.games647.scoreboardstats.pvpstats.DatabaseConfiguration.getSqlConfig(DatabaseConfiguration.java:121) [ScoreboardStats.jar:?]
23.10 02:34:57 [Server] INFO at com.github.games647.scoreboardstats.pvpstats.DatabaseConfiguration.loadConfiguration(DatabaseConfiguration.java:75) [ScoreboardStats.jar:?]
23.10 02:34:57 [Server] INFO at com.github.games647.scoreboardstats.pvpstats.Database.setupDatabase(Database.java:194) [ScoreboardStats.jar:?]
23.10 02:34:57 [Server] INFO at com.github.games647.scoreboardstats.ScoreboardStats.onEnable(ScoreboardStats.java:141) [ScoreboardStats.jar:?]
23.10 02:34:57 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot110.jar:git-Spigot-1e4dd71-4db0855]
23.10 02:34:57 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
23.10 02:34:57 [Server] INFO Using [com.github.games647.scoreboardstats.pvpstats.PathReader] to read the searchable class path
23.10 02:34:57 [Server] INFO DataSourcePool [ScoreboardStats] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
23.10 02:34:57 [Server] INFO SubClassFactory parent ClassLoader [com.github.games647.scoreboardstats.ReloadFixLoader]
23.10 02:34:57 [Server] INFO Entities enhanced[0] subclassed[1]
23.10 02:34:57 [Server] INFO runScript
23.10 02:34:57 [Server] INFO executing 1 of 1 create table IF NOT EXISTS player_stats ( id                        integer prim...
23.10 02:34:57 [Multicraft] Skipped 5 lines due to rate limit (30/s)
23.10 02:34:57 [Server] INFO Add-On load complete. Enabled 0 add-ons
```

**Comment by games647** [comment]
Duplicate #143
