### ISSUE TITLE
Possible bug remaining eban.properties

### ISSUE THREAD

**Issue by AngellitoX** [games647/ScoreboardStats#148]
Good afternoon, I'm having this message after starting my server after the new plugin release:

[21:29:34] [Server thread/INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.9.15
[21:29:34] [Server thread/INFO]: [ScoreboardStats] Registered replacers: [PlayerPingVariable, BukkitGlobalVariables, BungeeCordVariables, GeneralVariables, BukkitVariables, VaultVariables]
[21:29:34] [Server thread/ERROR]: ebean.properties not found
[21:29:34] [Server thread/INFO]: Using [com.github.games647.scoreboardstats.pvpstats.PathReader] to read the searchable class path
[21:29:34] [Server thread/INFO]: DataSourcePool [ScoreboardStats] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[21:29:34] [Server thread/INFO]: SubClassFactory parent ClassLoader [com.github.games647.scoreboardstats.ReloadFixLoader]
[21:29:34] [Server thread/INFO]: Entities enhanced[0] subclassed[1]
[21:29:34] [Server thread/INFO]: runScript
[21:29:34] [Server thread/INFO]: executing 1 of 1 create table IF NOT EXISTS player_stats ( id                        integer prim...
[21:29:34] [Server thread/INFO]: ... end of script

Is this still a bug or something?

Thank you so much for further help, and have a great day!

**Comment by games647** [comment]
It's not a bug. Just a debug message. So there is no need to fix it.

**Comment by Someone-NEW** [comment]
Hi yes here is need to be fixed i just will that all plugins work perfekt without any crazy spam messages, errors, what the hell some Small owners know? just make him a panic sory but this is anoying.
[00:50:47] [Server thread/INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.9.16
[00:50:47] [Server thread/INFO]: [ScoreboardStats] Path not fond disabled-worlds-whitelist
[00:50:47] [Server thread/INFO]: [ScoreboardStats] Registered replacers: [BukkitGlobalVariables, BungeeCordVariables, PlayerPingVariable, GeneralVariables, BukkitVariables, VaultVariables]
[00:50:47] [Server thread/ERROR]: ebean.properties not found
[00:50:47] [Server thread/INFO]: Using [com.github.games647.scoreboardstats.pvpstats.PathReader] to read the searchable class path
[00:50:47] [Server thread/INFO]: DataSourcePool [ScoreboardStats] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[00:50:47] [Server thread/INFO]: SubClassFactory parent ClassLoader [com.github.games647.scoreboardstats.ReloadFixLoader]
[00:50:51] [Server thread/INFO]: Entities enhanced[0] subclassed[1]
[00:50:51] [Server thread/INFO]: runScript
[00:50:51] [Server thread/INFO]: executing 1 of 1 create table IF NOT EXISTS player_stats ( id                        integer prim...
[00:50:51] [Server thread/INFO]: ... end of script

I use your latest release and when you just not find any time to fix this eeven you know this spam than i have no comment.
Anyway thank you for your time.

**Comment by Someone-NEW** [comment]
And here:
[00:50:53] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
java.lang.RuntimeException: No Mgr found for [] class java.util.ArrayList
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:357) ~[spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[spigot-1.10.2-R0.1-SNAPSHOT.jar:git-Spigot-570526c-c1b529e]
	at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:155) ~[?:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$2(Database.java:230) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_66]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by games647** [comment]
Spam? It's just one message???

About the second error: Yes I'll fix that, but there is another ticket about it. I'll replace ebean
in in the next version.

**Comment by Someone-NEW** [comment]
Thank you
