### ISSUE TITLE
receiver cannot be NULL

### ISSUE THREAD

**Issue by Eufranio** [games647/ScoreboardStats#149]
Look:

```
[00:35:59 WARN]: [ScoreboardStats] Task #916 for ScoreboardStats v0.9.15 generated an exception
java.lang.IllegalArgumentException: receiver cannot be NULL.
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:802) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:796) ~[?:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketFactory.sendPacket(PacketFactory.java:93) ~[?:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.Objective.<init>(Objective.java:44) ~[?:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.Objective.<init>(Objective.java:34) ~[?:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PlayerScoreboard.createSidebarObjective(PlayerScoreboard.java:68) ~[?:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.createScoreboard(PacketSbManager.java:85) ~[?:?]
        at com.github.games647.scoreboardstats.scoreboard.DelayedShowTask.run(DelayedShowTask.java:35) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```
This one happens randomly, and kicks some players.

And:
```
[00:33:46 INFO]: [ScoreboardStats] Registered replacers: [BungeeCordVariables, BukkitGlobalVariables, PlayerPingVariable, GeneralVariables, VaultVariables, BukkitVariables]
[00:33:46 INFO]: DatabasePlatform name:ScoreboardStats platform:mysql
[00:33:46 INFO]: SubClassFactory parent ClassLoader [com.github.games647.scoreboardstats.ReloadFixLoader]
[00:33:47 INFO]: Entities enhanced[0] subclassed[1]
[00:33:47 ERROR]: Error registering MBean[Ebean:server=ScoreboardStats3]
java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_111]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:585) ~[?:1.8.0_111]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848) ~[?:1.8.0_111]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322) ~[?:1.8.0_111]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:1.8.0_111]
        at com.avaje.ebeaninternal.server.core.DefaultServer.registerMBeans(DefaultServer.java:389) [DefaultServer.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:226) [DefaultServerFactory.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:64) [DefaultServerFactory.class:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) [EbeanServerFactory.class:?]
        at com.github.games647.scoreboardstats.pvpstats.Database.setupDatabase(Database.java:205) [ScoreboardStats(3).jar:?]
        at com.github.games647.scoreboardstats.ScoreboardStats.onReload(ScoreboardStats.java:190) [ScoreboardStats(3).jar:?]
        at com.github.games647.scoreboardstats.commands.ReloadCommand.onCommand(ReloadCommand.java:19) [ScoreboardStats(3).jar:?]
        at com.github.games647.scoreboardstats.commands.SidebarCommands.onCommand(SidebarCommands.java:52) [ScoreboardStats(3).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.58]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.58]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[00:33:47 INFO]: runScript
[00:33:47 INFO]: executing 1 of 1 create table IF NOT EXISTS player_stats ( id                        integer auto...
[00:33:47 INFO]: ... end of script
```
This happens when using the plugin with MySQL. Using ScoreboardStats v0.9.15.

**Comment by games647** [comment]
The last one can be ignored.

**Comment by Eufranio** [comment]
Is it normal?
```
[01:05:17 ERROR]: [ScoreboardStats] null
javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[update player_stats set mobkills=? where id=? and uuid=? and playername=? and kills=? and deaths=? and mobkills=? and killstreak=? and last_online=?] bind[null]
        at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:123) ~[DmlHandler.class:?]
        at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:106) ~[UpdateHandler.class:?]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105) ~[DmlBeanPersister.class:?]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:85) ~[DmlBeanPersister.class:?]
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:110) ~[DefaultPersistExecute.class:?]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:531) ~[PersistRequestBean.class:?]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:557) ~[PersistRequestBean.class:?]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:430) ~[DefaultPersister.class:?]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.forceUpdate(DefaultPersister.java:203) ~[DefaultPersister.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1615) ~[DefaultServer.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1605) ~[DefaultServer.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServer.update(DefaultServer.java:1584) ~[DefaultServer.class:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_111]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_111]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_111]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_111]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_111]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_111]
        at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$4(Database.java:237) ~[ScoreboardStats(3).jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by games647** [comment]
@Eufranio Use multiple servers the same table?

**Comment by Eufranio** [comment]
No. Also, the database is SQLite

**Comment by Eufranio** [comment]
I'm receiving the first error again.
```
[20:47:15 WARN]: [ScoreboardStats] Task #3309 for ScoreboardStats v0.9.15 generated an exception
java.lang.IllegalArgumentException: receiver cannot be NULL.
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:802) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:796) ~[ProtocolLib.jar:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketFactory.sendPacket(PacketFactory.java:93) ~[ScoreboardStats(3).jar:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.Objective.<init>(Objective.java:44) ~[ScoreboardStats(3).jar:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.Objective.<init>(Objective.java:34) ~[ScoreboardStats(3).jar:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PlayerScoreboard.createSidebarObjective(PlayerScoreboard.java:68) ~[ScoreboardStats(3).jar:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.createScoreboard(PacketSbManager.java:85) ~[ScoreboardStats(3).jar:?]
        at com.github.games647.scoreboardstats.scoreboard.DelayedShowTask.run(DelayedShowTask.java:35) ~[ScoreboardStats(3).jar:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Eufranio** [comment]
When there will be a new build?
