### ISSUE TITLE
Plugin Incompatibily: Disease and Thirty 

### ISSUE THREAD

**Issue by MackleyMag** [games647/ScoreboardStats#151]
This error is showed when I put the variables  '%thirst%', '%sick%' And '%temp%' on my ScoreboardStats config file and a Player connect. After this, the result in game is a -1 value at the places of this variables.

[ScoreboardStats] Task #30 for ScoreboardStats v0.9.15 generated an exception
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_111]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.getScoreLegacy(ReplaceManager.java:339) ~[?:?]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:250) ~[?:?]
	at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.createScoreboard(PacketSbManager.java:98) ~[?:?]
	at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.onUpdate(PacketSbManager.java:53) ~[?:?]
	at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[16:43:50] [Server thread/WARN]: [ScoreboardStats] Task #30 for ScoreboardStats v0.9.15 generated an exception
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_111]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.getScoreLegacy(ReplaceManager.java:339) ~[?:?]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:250) ~[?:?]
	at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.sendUpdate(PacketSbManager.java:170) ~[?:?]
	at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.onUpdate(PacketSbManager.java:55) ~[?:?]
	at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[16:43:50] [Server thread/WARN]: [ScoreboardStats] Task #30 for ScoreboardStats v0.9.15 generated an exception
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_111]
	at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_111]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.getScoreLegacy(ReplaceManager.java:339) ~[?:?]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:250) ~[?:?]
	at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.sendUpdate(PacketSbManager.java:170) ~[?:?]
	at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.onUpdate(PacketSbManager.java:55) ~[?:?]
	at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-691628a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[16:44:18] [Server thread/INFO]: [ScoreboardStats] Registered replacers: [BungeeCordVariables, PlayerPingVariable, BukkitGlobalVariables, GeneralVariables, BukkitVariables, VaultVariables, McmmoVariables]

**Comment by games647** [comment]
Duplicate #150
