### ISSUE TITLE
Error on MC1.11 Spigot

### ISSUE THREAD

**Issue by DaDMaR** [games647/ScoreboardStats#152]
was working with MC1.10.2  now on MC1.11 this

java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_101]
        at java.util.AbstractList.add(Unknown Source) ~[?:1.8.0_101]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.getScoreLegacy(ReplaceManager.java:339) ~[?:?]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:250) ~[?:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.createScoreboard(PacketSbManager.java:98) ~[?:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.onUpdate(PacketSbManager.java:53) ~[?:?]
        at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:46) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-31fef09-78c7614]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[21:50:13 INFO]: DaDMaR777 issued server command: /we cui

**Comment by games647** [comment]
Duplicate #151
