### ISSUE TITLE
Ping not working and error

### ISSUE THREAD

**Issue by Eufranio** [games647/ScoreboardStats#153]
http://hastebin.com/asiyodotih.vbs

ScoreboardStats 0.9.5
Thermos 1.7.10 B58

**Comment by games647** [comment]
It tried it, but it works for me. Do you have a plugin or mod which modifies the player class?

**Comment by Eufranio** [comment]
Only mod I know that modify the player class is Mo' Bends that I'm using, but why would it modify the ping stuff? (its a visual mod) 

My plugins: Plugins (47): aUCVault, LuckPerms, dynmap, Itemizer, WorldEdit, EmptyWorldGenerator, Skript, OpenInv, Offline_Teleporter, ClearLag, AutoMessage, PlugMan, VipZeroFIX, WorldBorder, ConsoleSpamFix, ProtocolLib, WorldGuard, AutoSaveWorld, MagiUtils, MultiWorld, ChatReaction, eZProtector, AsyncWorldEdit, Magi-GUI, MagiKits, Vault, MyCommand, BetterAlias, BungeeTabListPlus, ItemRestrict, FastLogin, Essentials, ScoreboardStats, RandomTP, Trading, HolographicDisplays, CutePortals, VipZero, Citizens, Legendchat, TagsGUI-2.0, DiscordSRV, ChestCommands, EssentialsSpawn, AuthMe, AuthMeBridge, FramePicture

Mods: www.magitechserver.com/mods

**Comment by Eufranio** [comment]
Is it a debug? Can I get a testing build?

**Comment by games647** [comment]
>Only mod I know that modify the player class is Mo' Bends that I'm using, but why would it modify the ping stuff? (its a visual mod)

It's also enough if it's just override the class. I uploaded a debug which you could try.

**Comment by Eufranio** [comment]
Where can I download?

**Comment by games647** [comment]
https://dev.bukkit.org/bukkit-plugins/scoreboardstats/files/53-socreboard-stats-v0-9-16/

**Comment by Eufranio** [comment]
http://hastebin.com/qijitabubi.vbs

**Comment by games647** [comment]
#142

**Comment by Eufranio** [comment]
The plugin won't be showing the scoreboard too...

**Comment by games647** [comment]
https://github.com/games647/ScoreboardStats/issues/142#issuecomment-255083476

**Comment by Eufranio** [comment]
No debug message, only the same error:
```[02:12:22 WARN]: [ScoreboardStats] Replacer occurred an error: com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable@67c6ba0c[getHandleMethod=public net.minecraft.entity.player.EntityPlayerMP org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.getHandle(),pingField=<null>,plugin=<null>,async=false,global=false,constant=false,description=&cNo description,variables={ping},enabled=false] for {1} So it will be removed to prevent future errors
java.lang.NullPointerException
        at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.setMCPCPing(PlayerPingVariable.java:72) ~[ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.getReflectionPing(PlayerPingVariable.java:47) ~[ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.onReplace(PlayerPingVariable.java:31) ~[ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:254) [ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.createScoreboard(PacketSbManager.java:98) [ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.onUpdate(PacketSbManager.java:53) [ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:46) [ScoreboardStats(6).jar:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[02:12:22 WARN]: [ScoreboardStats] Replacer occurred an error: com.github.games647.scoreboardstats.variables.defaults.PlaceHolderVariables@52cb7753[plugin=PlaceholderAPI v2.6.0,async=false,global=false,constant=false,description=&cNo description,variables={mycommand_*},enabled=false] for {1} So it will be removed to prevent future errors
java.lang.NoSuchMethodError: guava10.com.google.common.primitives.Doubles.tryParse(Ljava/lang/String;)Ljava/lang/Double;
        at com.github.games647.scoreboardstats.variables.defaults.PlaceHolderVariables.onReplace(PlaceHolderVariables.java:53) ~[ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.getScoreLegacy(ReplaceManager.java:333) [ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:251) [ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.createScoreboard(PacketSbManager.java:98) [ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.onUpdate(PacketSbManager.java:53) [ScoreboardStats(6).jar:?]
        at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:46) [ScoreboardStats(6).jar:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by games647** [comment]
Why you can't compile it?

**Comment by HeyZeer0** [comment]
I can't compile too, aparently some maven dependecies are broken :(

**Comment by games647** [comment]
https://github.com/games647/ScoreboardStats/releases/tag/0.9.16

**Comment by Eufranio** [comment]
```[11:47:53 INFO]: [ScoreboardStats] Looking for ping field
[11:47:53 INFO]: [ScoreboardStats] Ping field null for GCEntityPlayerMP['DJ_Domco'/2520, l='world', x=-2424.73, y=67.00, z=1745.57](DJ_Domco at -2424.725568383232,67.0,1745.566744296505)```
That's the debug.

**Comment by games647** [comment]
What could GC stands for?

**Comment by Eufranio** [comment]
GalactiCraft probably, an mod from my modpack

**Comment by Eufranio** [comment]
and its open source yay https://github.com/micdoodle8/Galacticraft

**Comment by Eufranio** [comment]
Nope...
```
[22:16:07 INFO]: [ScoreboardStats] Looking for ping field
[22:16:07 INFO]: [ScoreboardStats] Looking for player clazz class net.minecraft.entity.player.EntityPlayerMP
[22:16:07 INFO]: [ScoreboardStats] Ping field public int net.minecraft.entity.player.EntityPlayerMP.field_71138_i for GCEntityPlayerMP['Nonkill'/1910, l='world', x=3258.54, y=66.48, z=1177.53](Nonkill at 3258.5417832404746,66.4807108763317,1177.5276231114365)
```
and the scoreboard still not showing up in the server.

**Comment by Eufranio** [comment]
Okay, disabling `compatibilityMode` fixes the issue, you may want fix this. Now the scoreboard is showing, but I can't use ColoredTags...

**Comment by Eufranio** [comment]
**rip**
```
[23:08:01 INFO]: [ScoreboardStats] Looking for ping field
[23:08:01 WARN]: [ScoreboardStats] Replacer occurred an error: com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable@6802331f[getHandleMethod=public net.minecraft.entity.player.EntityPlayerMP org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.getHandle(),pingField=<null>,plugin=ScoreboardStats v0.1,async=false,global=false,constant=false,description=&cNo description,variables={ping},enabled=false] for {1} So it will be removed to prevent future errors
java.lang.RuntimeException: java.lang.IllegalAccessException: Class com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable can not access a member of class net.minecraft.entity.player.EntityPlayerMP with modifiers "private static final"
        at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.getReflectionPing(PlayerPingVariable.java:59) ~[ScoreboardStats.jar:?]
        at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.onReplace(PlayerPingVariable.java:31) ~[ScoreboardStats.jar:?]
        at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:254) [ScoreboardStats.jar:?]
        at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.createScoreboard(BukkitScoreboardManager.java:75) [ScoreboardStats.jar:?]
        at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.onUpdate(BukkitScoreboardManager.java:105) [ScoreboardStats.jar:?]
        at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:46) [ScoreboardStats.jar:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalAccessException: Class com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable can not access a member of class net.minecraft.entity.player.EntityPlayerMP with modifiers "private static final"
        at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102) ~[?:1.8.0_111]
        at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296) ~[?:1.8.0_111]
        at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288) ~[?:1.8.0_111]
        at java.lang.reflect.Field.get(Field.java:390) ~[?:1.8.0_111]
        at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.findEntityPlayer(PlayerPingVariable.java:107) ~[ScoreboardStats.jar:?]
        at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.findEntityPlayer(PlayerPingVariable.java:114) ~[ScoreboardStats.jar:?]
        at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.setMCPCPing(PlayerPingVariable.java:74) ~[ScoreboardStats.jar:?]
        at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.getReflectionPing(PlayerPingVariable.java:47) ~[ScoreboardStats.jar:?]
        ... 12 more
```
