### ISSUE TITLE
Disease and Thist

### ISSUE THREAD

**Issue by MackleyMag** [games647/ScoreboardStats#156]
![image](https://cloud.githubusercontent.com/assets/11464046/20669945/e9a433ac-b55d-11e6-9bbb-f1dd2841c4f2.png)
This continue happens, Im now on version 9.16 but now there is no error on console anymore
some times, on or another turn to work when I reboot the server, but if I keep trying to reboot to see if that works for both, turns to the first image 
![image](https://cloud.githubusercontent.com/assets/11464046/20670049/49616814-b55e-11e6-9cf2-cb8df3606bc2.png)
If i try /sb reload,
[ScoreboardStats] null
java.lang.RuntimeException: No Mgr found for [] class java.util.ArrayList
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:357) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[spigot-1.11.jar:git-Spigot-f950f8e-ad0e4b3]
	at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:155) ~[?:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$2(Database.java:230) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
an then
![image](https://cloud.githubusercontent.com/assets/11464046/20669945/e9a433ac-b55d-11e6-9bbb-f1dd2841c4f2.png)

**Comment by games647** [comment]
Try it without reloading

**Comment by MackleyMag** [comment]
same result. I start the server, no errors on console and the stats is -1 on the variables.
![image](https://cloud.githubusercontent.com/assets/11464046/20673994/58ebf3e8-b56e-11e6-8490-ebc2b3bd5fd7.png)
Like I said before, sometimes is the disease and other times is the Thirst. Some times happens the both show -1 and sometimes is anyone. but when I close my server, starts the thing again

**Comment by MackleyMag** [comment]
![image](https://cloud.githubusercontent.com/assets/11464046/20674155/f20f21e4-b56e-11e6-97a8-a772a2912daf.png)
![image](https://cloud.githubusercontent.com/assets/11464046/20674170/00335a06-b56f-11e6-8080-c39bf262646c.png)
both plugins are detecting the ScoreBoard Stats and registering the variables.

**Comment by games647** [comment]
Could you send the complete log?

**Comment by MackleyMag** [comment]
I solved the problem downgrading my version of ScoreboardStats to ScoreboardStats9.12. Now, there is no errors on console and all the variables are working all the time.

**Comment by TheChampTF** [comment]
Thirst -1 or Killstreak , Mob Kills also -1 happens when you have yet to be active.

Move around and it worked for me

**Comment by MackleyMag** [comment]
for the latest release, Thirst and Disease are broken. The others I don't know. Like i said, I downgrade my version to 9.12 and both of them are working again.
