### ISSUE TITLE
No Mgr found for [] class java.util.ArrayList

### ISSUE THREAD

**Issue by DardBrinza** [games647/ScoreboardStats#160]
1) I get this error, latest PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) and latest scoreboardstats

```
[21:01:40 ERROR]: [ScoreboardStats] null
java.lang.RuntimeException: No Mgr found for [] class java.util.ArrayList
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:357) ~[Spigot.jar:git-Spigot-5f38d38-18fbb24]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[Spigot.jar:git-Spigot-5f38d38-18fbb24]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[Spigot.jar:git-Spigot-5f38d38-18fbb24]
        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[Spigot.jar:git-Spigot-5f38d38-18fbb24]
        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[Spigot.jar:git-Spigot-5f38d38-18fbb24]
        at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:155) ~[?:?]
        at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$2(Database.java:230) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

2) If i "compatibilityMode: true" my scoreboard dissapear

**Comment by games647** [comment]
Duplicate #155
