### ISSUE TITLE
A PRIMARY KEY constraint failed

### ISSUE THREAD

**Issue by Dimatert9** [games647/ScoreboardStats#161]
```
[16:12:14] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[[SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: player_stats.id)]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:156) ~[?:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$3(Database.java:236) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_92]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: player_stats.id)
	at org.sqlite.core.DB.newSQLException(DB.java:909) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.core.DB.newSQLException(DB.java:921) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.core.DB.execute(DB.java:825) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.core.DB.executeUpdate(DB.java:863) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:164) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:74) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:158) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	... 20 more

[16:13:14] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[[SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: player_stats.id)]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:156) ~[?:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$3(Database.java:236) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_92]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_PRIMARYKEY]  A PRIMARY KEY constraint failed (UNIQUE constraint failed: player_stats.id)
	at org.sqlite.core.DB.newSQLException(DB.java:909) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.core.DB.newSQLException(DB.java:921) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.core.DB.execute(DB.java:825) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.core.DB.executeUpdate(DB.java:863) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:164) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:74) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:158) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	... 20 more
[16:14:14] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[statement is not executing]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:156) ~[?:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$3(Database.java:236) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_92]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.sql.SQLException: statement is not executing
	at org.sqlite.core.CoreStatement.checkOpen(CoreStatement.java:50) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.core.CorePreparedStatement.batch(CorePreparedStatement.java:117) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.setInt(JDBC3PreparedStatement.java:324) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.setInt(ExtendedPreparedStatement.java:297) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.type.DataBind.setInt(DataBind.java:86) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:45) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:35) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.bind(BeanProperty.java:663) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bindInternal(DmlHandler.java:264) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bind(DmlHandler.java:223) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:102) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:91) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.InsertMeta.bind(InsertMeta.java:156) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.bind(InsertHandler.java:133) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:98) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	... 20 more
[16:15:14] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[statement is not executing]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:156) ~[?:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$3(Database.java:236) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_92]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.sql.SQLException: statement is not executing
	at org.sqlite.core.CoreStatement.checkOpen(CoreStatement.java:50) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.core.CorePreparedStatement.batch(CorePreparedStatement.java:117) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.setInt(JDBC3PreparedStatement.java:324) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.setInt(ExtendedPreparedStatement.java:297) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.type.DataBind.setInt(DataBind.java:86) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:45) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.type.ScalarTypeInteger.bind(ScalarTypeInteger.java:35) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.deploy.BeanProperty.bind(BeanProperty.java:663) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bindInternal(DmlHandler.java:264) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.bind(DmlHandler.java:223) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:102) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dmlbind.BindableIdScalar.dmlBind(BindableIdScalar.java:91) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.InsertMeta.bind(InsertMeta.java:156) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.bind(InsertHandler.java:133) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:98) ~[Spigot.jar:git-Spigot-f950f8e-7f31326]
	... 20 more
```
also scoreboard is not appears
compiled from latest source

**Comment by games647** [comment]
Ebean is just totally buggy

**Comment by games647** [comment]
Just downgrade
