### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by andris155** [games647/ScoreboardStats#167]
```
01.01 18:42:21 [Server] ERROR Error inserting profiles
01.01 18:42:21 [Server] INFO org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_NOTNULL]  A NOT NULL constraint failed (NOT NULL constraint failed: player_stats.last_online)
01.01 18:42:21 [Server] INFO at org.sqlite.core.DB.newSQLException(DB.java:909) ~[patched_1.11.jar:git-Paper-976]
01.01 18:42:21 [Server] INFO at org.sqlite.core.DB.newSQLException(DB.java:921) ~[patched_1.11.jar:git-Paper-976]
01.01 18:42:21 [Server] INFO at org.sqlite.core.DB.throwex(DB.java:886) ~[patched_1.11.jar:git-Paper-976]
01.01 18:42:21 [Server] INFO at org.sqlite.core.DB.executeBatch(DB.java:774) ~[patched_1.11.jar:git-Paper-976]
01.01 18:42:21 [Server] INFO at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:79) ~[patched_1.11.jar:git-Paper-976]
01.01 18:42:21 [Server] INFO at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[?:?]
01.01 18:42:21 [Server] INFO at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[?:?]
01.01 18:42:21 [Server] INFO at com.github.games647.scoreboardstats.pvpstats.Database.insert(Database.java:256) ~[?:?]
01.01 18:42:21 [Server] INFO at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:191) ~[?:?]
01.01 18:42:21 [Server] INFO at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$3(Database.java:361) ~[?:?]
01.01 18:42:21 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
01.01 18:42:21 [Server] INFO at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
01.01 18:42:21 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
01.01 18:42:21 [Server] INFO at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
01.01 18:42:21 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
01.01 18:42:21 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
01.01 18:42:21 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by games647** [comment]
Please use better titles next time.
