### ISSUE TITLE
Failed to initialize pool

### ISSUE THREAD

**Issue by Eufranio** [games647/ScoreboardStats#172]
Just updated to your latest release and the plugin won't work anymore.
```
Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: org.sqlite.Conn.isValid(I)Z
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:512) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
        at com.github.games647.scoreboardstats.pvpstats.Database.setupDatabase(Database.java:314) ~[?:?]
        at com.github.games647.scoreboardstats.ScoreboardStats.onReload(ScoreboardStats.java:151) ~[?:?]
        at com.github.games647.scoreboardstats.commands.ReloadCommand.onCommand(ReloadCommand.java:19) ~[?:?]
        at com.github.games647.scoreboardstats.commands.SidebarCommands.onCommand(SidebarCommands.java:52) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
        ... 8 more
Caused by: java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z
        at com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:400) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:375) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:105) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71) ~[?:?]
        at com.github.games647.scoreboardstats.pvpstats.Database.setupDatabase(Database.java:314) ~[?:?]
        at com.github.games647.scoreboardstats.ScoreboardStats.onReload(ScoreboardStats.java:151) ~[?:?]
        at com.github.games647.scoreboardstats.commands.ReloadCommand.onCommand(ReloadCommand.java:19) ~[?:?]
        at com.github.games647.scoreboardstats.commands.SidebarCommands.onCommand(SidebarCommands.java:52) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
        ... 8 more
```

**Comment by Eufranio** [comment]
Sorry, duplicated of https://github.com/games647/ScoreboardStats/issues/170, didn't see any releases.

**Comment by games647** [comment]
>didn't see any releases.

The new version should be on devBukkit since 16 hours.
