### ISSUE TITLE
Waiting for database

### ISSUE THREAD

**Issue by SlimeDog** [games647/ScoreboardStats#175]
Environment: Spigot 1.11.2 latest, SS 1.10.1 latest.

On server shutdown:

> [10:32:09] [Server thread/INFO]: [ScoreboardStats] Now saving the stats to the database. This could take a while.
[10:47:09] [Server thread/INFO]: [HeadsPlugin] Disabling HeadsPlugin v1.4.2
[10:47:09] [Server thread/INFO]: [^[[0;32;22mMyPet^[[m] ^[[mDisabling MyPet v2.2.9^[[m
[10:47:09] [ScoreboardStats-Database/ERROR]: [ScoreboardStats] null
java.util.concurrent.CancellationException
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.get(CraftFuture.java:68) ~[spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftFuture.get(CraftFuture.java:42) ~[spigot-1.11.2.jar-2017-01-11-1706:git-Spigot-7d78b81-775f1e1]
        at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$3(Database.java:354) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by games647** [comment]
It tried to update the leaderboard in the same second. You can ignore it for now. It shouldn't have any effects.

**Comment by SlimeDog** [comment]
OK, thanks.

**Comment by SlimeDog** [comment]
The effect is that the server never cleanly shuts down. I am experiencing this more frequently on Spigot 1.12. Please fix.
