### ISSUE TITLE
ScoreboardStats Error

### ISSUE THREAD

**Issue by DarkNOD** [games647/ScoreboardStats#176]
Hello,
Can you fix the error please?

[17:52:34 WARN]: [ScoreboardStats] Task #369464 for ScoreboardStats v0.9.9 generated an exception
java.lang.UnsupportedOperationException: The method getUniqueId is not supported for temporary players.
at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[?:?]
at com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$39b81c9.getUniqueId() ~[?:?]
at com.github.games647.scoreboardstats.scoreboard.protocol.PacketSbManager.getScoreboard(PacketSbManager.java:44) ~[?:?]
at com.github.games647.scoreboardstats.scoreboard.protocol.PacketListener$1.run(PacketListener.java:90) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-76236cb-62a2169]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-76236cb-62a2169]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-76236cb-62a2169]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-76236cb-62a2169]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-76236cb-62a2169]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-76236cb-62a2169]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]

**Comment by games647** [comment]
Please use the latest version

**Comment by DarkNOD** [comment]
Sorry dude but i use the last version
