### ISSUE TITLE
A UNIQUE constraint failed

### ISSUE THREAD

**Issue by Fiks75** [games647/ScoreboardStats#178]
Hi. This error paperSpigot 1.11.2. Please fix it

[12:20:09 ERROR]: [ScoreboardStats] Error inserting profiles
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: player_stats.uuid)
	at org.sqlite.core.DB.newSQLException(DB.java:909) ~[patched_1.11.2.jar:git-Paper-1040]
	at org.sqlite.core.DB.newSQLException(DB.java:921) ~[patched_1.11.2.jar:git-Paper-1040]
	at org.sqlite.core.DB.throwex(DB.java:886) ~[patched_1.11.2.jar:git-Paper-1040]
	at org.sqlite.core.DB.executeBatch(DB.java:774) ~[patched_1.11.2.jar:git-Paper-1040]
	at org.sqlite.core.CorePreparedStatement.executeBatch(CorePreparedStatement.java:79) ~[patched_1.11.2.jar:git-Paper-1040]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[?:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[?:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.insert(Database.java:258) ~[?:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.save(Database.java:191) ~[?:?]
	at com.github.games647.scoreboardstats.pvpstats.Database.lambda$setupDatabase$3(Database.java:363) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by games647** [comment]
Please send me your database config.

**Comment by games647** [comment]
Should be fixed now.
