### ISSUE TITLE
Error trying to access ping field

### ISSUE THREAD

**Issue by Eufranio** [games647/ScoreboardStats#186]
This error just popped up when the server was starting.
```
> [16:54:46 INFO]: [ScoreboardStats] Looking for ping field
> [16:54:46 WARN]: [ScoreboardStats] Replacer occurred an error: com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable@57304d4a[getHandleM
ethod=public net.minecraft.entity.player.EntityPlayerMP org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.getHandle(),pingField=<null>,plugin=ScoreboardStats 
v0.1,async=false,global=false,constant=false,description=&cNo description,variables={ping},enabled=false] for {1} So it will be removed to prevent future erro
rs
java.lang.RuntimeException: java.lang.IllegalAccessException: Class com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable can not access a
 member of class net.minecraft.entity.player.EntityPlayerMP with modifiers "private static final"
    at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.getReflectionPing(PlayerPingVariable.java:59) ~[ScoreboardStats.jar:?]
    at com.github.games647.scoreboardstats.variables.defaults.PlayerPingVariable.onReplace(PlayerPingVariable.java:31) ~[ScoreboardStats.jar:?]
    at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:254) [ScoreboardStats.jar:?]
    at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.createScoreboard(BukkitScoreboardManager.java:75) [ScoreboardStats.jar:?]
    at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.onUpdate(BukkitScoreboardManager.java:105) [ScoreboardStats.jar:?]
    at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:46) [ScoreboardStats.jar:?]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [CraftTask.class:1.7.10-1614.58]
    at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
```

**Comment by games647** [comment]
The variable is too deeply nested and obfuscated, so it's hard to fix it really.
