### ISSUE TITLE
Massive Faction - Log Spam

### ISSUE THREAD

**Issue by Saiee** [games647/ScoreboardStats#36]
Plugins:

ScorebordStats for 1.8

FactionsUUID

----------------------
Massive Spam in the console. It starts only when a player is online.

----------------------

[15:22:54] [Server thread/WARN]: [ScoreboardStats] Task #39 for ScoreboardStats v0.8.4 generated an exception
java.lang.NoSuchFieldError: i
 at com.github.games647.scoreboardstats.variables.FactionsVariables.getOldFactionScore(FactionsVariables.java:72) ~[?:?]
 at com.github.games647.scoreboardstats.variables.FactionsVariables.getScoreValue(FactionsVariables.java:41) ~[?:?]
 at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:111) ~[?:?]
 at com.github.games647.scoreboardstats.protocol.PacketSbManager.sendUpdate(PacketSbManager.java:69) ~[?:?]
 at com.github.games647.scoreboardstats.protocol.PacketSbManager.createScoreboard(PacketSbManager.java:105) ~[?:?]
 at com.github.games647.scoreboardstats.protocol.PacketSbManager.sendUpdate(PacketSbManager.java:58) ~[?:?]
 at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:51) ~[?:?]
 at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-9a88a38-e2c4f20]
 at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-9a88a38-e2c4f20]
 at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-9a88a38-e2c4f20]
 at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-9a88a38-e2c4f20]
 at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-9a88a38-e2c4f20]
 at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-9a88a38-e2c4f20]
 at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by Saiee** [comment]
Will it ever get fixed?
