### ISSUE TITLE
Random reload error

### ISSUE THREAD

**Issue by madtomic** [games647/ScoreboardStats#47]
[16:44:20 INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.8.5
[16:44:20 INFO]: SubClassFactory parent ClassLoader [com.github.games647.scorebo
ardstats.ReloadFixLoader]
[16:44:20 INFO]: Entities enhanced[0] subclassed[1]
[16:44:20 INFO]: runScript
[16:44:20 INFO]: executing 1 of 1 create table IF NOT EXISTS player_stats ( id
                      integer prim...
[16:44:20 INFO]: ... end of script
[16:44:20 INFO]: [ScoreboardStats] Registered replacers: [PlayerPingVariable, St
atsVariables, GeneralVariables, VaultVariables, McmmoVariables, FactionsVariable
s]
[16:44:20 ERROR]: Error occurred while enabling ScoreboardStats v0.8.5 (Is it up
 to date?)
java.lang.ClassCastException: com.github.games647.scoreboardstats.pvpstats.Playe
rStats$$EntityBean$ScoreboardStats cannot be cast to com.github.games647.scorebo
ardstats.pvpstats.PlayerStats
        at com.github.games647.scoreboardstats.pvpstats.Database.getCachedStats(
Database.java:58) ~[?:?]
        at com.github.games647.scoreboardstats.pvpstats.Database.loadAccountAsyn
c(Database.java:71) ~[?:?]
        at com.github.games647.scoreboardstats.SbManager.registerAll(SbManager.j
ava:100) ~[?:?]
        at com.github.games647.scoreboardstats.ScoreboardStats.onEnable(Scoreboa
rdStats.java:135) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[s
pigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:335) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.jav
a:356) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.
java:316) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.reload(CraftServer.java:74
6) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.Bukkit.reload(Bukkit.java:534) [spigot-1.8.jar:git-Spigot-
8a983f9-e81edfc]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:
25) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServe
r.java:646) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(Craf
tServer.java:632) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:
353) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:3
17) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:6
34) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:537) [spigot-1.8.jar:git-Spigot-8a983f9-e81edfc]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]

**Comment by games647** [comment]
Does it happen only after a reload?

**Comment by madtomic** [comment]
yes

**Comment by games647** [comment]
Did you replaced/updated the jar before the reload?

**Comment by madtomic** [comment]
no, just load and reload and got this error.

**Comment by madtomic** [comment]
greate!

**Comment by games647** [comment]
Thank you for the report. I found a memory leak because of this. :thumbsup:

**Comment by madtomic** [comment]
Cheers!
