### ISSUE TITLE
Scoreboard Updater could not contact dev.bukkit.org

### ISSUE THREAD

**Issue by hdglifezach** [games647/ScoreboardStats#50]
The players on my server can not see there stats on the server but the top 5 are still loading! here is what I get in the console!

[22:30:57] [Server thread/INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.8.5
[22:30:57] [Server thread/INFO]: Using [com.github.games647.scoreboardstats.pvpstats.PathReader] to read the searchable class path
[22:30:57] [Server thread/INFO]: DataSourcePool [ScoreboardStats] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[22:30:57] [Server thread/INFO]: DatabasePlatform name:ScoreboardStats platform:mysql
[22:30:57] [Server thread/INFO]: SubClassFactory parent ClassLoader [com.github.games647.scoreboardstats.ReloadFixLoader]
[22:30:57] [Server thread/INFO]: Entities enhanced[0] subclassed[1]
[22:30:58] [Server thread/INFO]: runScript
[22:30:58] [Server thread/INFO]: executing 1 of 1 create table IF NOT EXISTS player_stats ( id                        integer auto...
[22:30:58] [Server thread/INFO]: ... end of script
[22:30:58] [Server thread/INFO]: [ScoreboardStats] Registered replacers: [VaultVariables, PlayerPingVariable, GeneralVariables, StatsVariables]
[22:30:58] [Server thread/INFO]: [FuelBomb] Enabling FuelBomb v2.5
[22:30:58] [Server thread/INFO]: [Fuelbomb] A new version is available: 2.6
[22:30:58] [Server thread/INFO]: [Fuelbomb] Get it from: http://dev.bukkit.org/bukkit-plugins/fuel-bomb/files/20-fuelbomb-v2-6/
[22:30:58] [Server thread/INFO]: [Fuelbomb] has been enabled | Plugin by Premx
[22:30:58] [Server thread/INFO]: [Fuelbomb] you use mode 1 !
[22:30:58] [Server thread/INFO]: [TheRiftDisguise] Enabling TheRiftDisguise v1.1
[22:30:58] [Server thread/INFO]: <<[ TheRiftDisguise ]>>  [ Version ]=[ 1.1 ] [ Successfully Loaded! ]
[22:30:58] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat vDev2.14.98
[22:30:58] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:30:58] [Server thread/INFO]: Done (8.245s)! For help, type "help" or "?"
[22:30:58] [Server thread/INFO]: [Buycraft] Authenticated with the specified Secret key.
[22:30:58] [Server thread/INFO]: [Buycraft] Plugin is now ready to be used.
[22:30:58] [Craft Scheduler Thread - 14/INFO]: [Vault] Checking for Updates ... 
[22:30:58] [User Authenticator #1/INFO]: UUID of player HDGLiFE_Zach is bcb3c749-f55f-4c15-a674-5cab2b210abf
[22:30:58] [pool-8-thread-2/INFO]: [Buycraft] Loaded 11 package(s) into the cache.
[22:30:58] [Craft Scheduler Thread - 14/WARN]: [Vault] Stable Version: 1.5.3 is out! You are still running version: 1.5.2
[22:30:58] [Craft Scheduler Thread - 14/WARN]: [Vault] Update at: http://dev.bukkit.org/server-mods/vault
[22:30:59] [Server thread/INFO]: HDGLiFE_Zach[/96.227.184.20:41856] logged in with entity id 52 at ([kits] 382.1676583126343, 62.0, 611.2013913958791)
[22:31:03] [Server thread/INFO]: [Lvl 0]  [Owner] HDGLiFE_Zach > a
[22:31:07] [Thread-20/ERROR]: [ScoreboardStats] The updater could not contact dev.bukkit.org for updating.
[22:31:07] [Thread-20/ERROR]: [ScoreboardStats] The site may be experiencing temporary downtime.
[22:31:07] [Thread-20/ERROR]: [ScoreboardStats] null
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.7.0_75]
	at java.net.SocketInputStream.read(SocketInputStream.java:152) ~[?:1.7.0_75]
	at java.net.SocketInputStream.read(SocketInputStream.java:122) ~[?:1.7.0_75]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442) ~[?:1.7.0_75]
	at sun.security.ssl.InputRecord.read(InputRecord.java:480) ~[?:1.7.0_75]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934) ~[?:1.7.0_75]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:891) ~[?:1.7.0_75]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:102) ~[?:1.7.0_75]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235) ~[?:1.7.0_75]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275) ~[?:1.7.0_75]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334) ~[?:1.7.0_75]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687) ~[?:1.7.0_75]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633) ~[?:1.7.0_75]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1324) ~[?:1.7.0_75]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[?:1.7.0_75]
	at com.github.games647.scoreboardstats.Updater.read(Updater.java:339) [ScoreboardStats.jar:0.8.5]
	at com.github.games647.scoreboardstats.Updater.runUpdater(Updater.java:383) [ScoreboardStats.jar:0.8.5]
	at com.github.games647.scoreboardstats.Updater.access$100(Updater.java:30) [ScoreboardStats.jar:0.8.5]
	at com.github.games647.scoreboardstats.Updater$UpdateRunnable.run(Updater.java:378) [ScoreboardStats.jar:0.8.5]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]

**Comment by games647** [comment]
That issue is not related to the updater:

>[22:31:07] [Thread-20/ERROR]: [ScoreboardStats] The updater could not contact dev.bukkit.org for updating.
>[22:31:07] [Thread-20/ERROR]: [ScoreboardStats] The site may be experiencing temporary downtime.

Could you send me your config as gist, pastebin, hastebin or similar entry?

**Comment by hdglifezach** [comment]
ok
config: http://pastebin.com/yQ6iDK2p
sql: http://pastebin.com/5MQAzSGS

**Comment by games647** [comment]
So you can see the temp-scoreboard, but not the normal one?

**Comment by hdglifezach** [comment]
Yes

**Comment by games647** [comment]
Which other plugins do you have?

**Comment by hdglifezach** [comment]
http://gyazo.com/bc0371cc22d36126db0a5fa7f885dd0e

**Comment by games647** [comment]
Why do you have pvpstatsscoreboard installed without pvp stats? I guess it sets an empty objective.
