### ISSUE TITLE
Error loading the Server

### ISSUE THREAD

**Issue by dorcu** [games647/ScoreboardStats#51]
[13:36:02 ERROR]: Error occurred while enabling ScoreboardStats v0.8.5 (Is it up
 to date?)
java.lang.IllegalArgumentException: Cannot set to an empty path
        at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[spigot
-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.configuration.MemorySection.set(MemorySection.java:163) ~[
spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.configuration.MemorySection.set(MemorySection.java:193) ~[
spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections
(YamlConfiguration.java:80) ~[spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections
(YamlConfiguration.java:78) ~[spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections
(YamlConfiguration.java:78) ~[spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlCo
nfiguration.java:68) ~[spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at com.github.games647.scoreboardstats.Settings.getConfigFromDisk(Settin
gs.java:263) ~[?:?]
        at com.github.games647.scoreboardstats.Settings.loadConfig(Settings.java
:199) ~[?:?]
        at com.github.games647.scoreboardstats.ScoreboardStats.onEnable(Scoreboa
rdStats.java:92) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[s
pigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:335) [spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) [spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.jav
a:356) [spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.
java:316) [spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:4
02) [spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:3
70) [spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:3
25) [spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.jav
a:211) [spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java
:505) [spigot-1.8_V2.0.jar:git-Spigot-ed3e3af-ee6d0fa]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]

**Comment by games647** [comment]
Could you send me your configuration? (with Github Gist, pastebin, hastebin or similar)

**Comment by dorcu** [comment]
It has've found the error. If I put this configuration gives error:

'&9Exp.': '%exp%'

But if I put it without a point works well:

'&9Exp': '%exp%'

**Comment by games647** [comment]
It should work with the dot too.

**Comment by dorcu** [comment]
In my case it does not work. I removed the point and work well.

**Comment by games647** [comment]
It looks like it's a Bukkit issue.
