### ISSUE TITLE
Invalid Format: 2.8.7Beta

### ISSUE THREAD

**Issue by ireeskenz** [games647/ScoreboardStats#80]
Hi, i got a problem with our beautiful plugin in 1.9, "java.lang.Illegal.ArgumentException: Invalid format: 2.8.7Beta", thanks.

**Comment by games647** [comment]
The plugin should not extend from the default replacer class.

**Comment by ireeskenz** [comment]
Ok and how can i fix it? :)

**Comment by games647** [comment]
Who is the author of this plugin?

**Comment by ireeskenz** [comment]
it's you but do you have any solution?

**Comment by games647** [comment]
No I meant the other plug in.

**Comment by ireeskenz** [comment]
Sorry, i use v.0.9.7
I mean your plugin is nice !
`[15:42:12] [Server thread/INFO]: [ScoreboardStats] Enabling ScoreboardStats v0.9.7
[15:42:12] [Server thread/INFO]: [ScoreboardStats] Found plugin: HealthBar
[15:42:12] [Server thread/INFO]: [ScoreboardStats] You are using plugins that requires to activate compatibilityMode
[15:42:12] [Server thread/INFO]: [ScoreboardStats] Otherwise the plugins won't work
[15:42:12] [Server thread/INFO]: [ScoreboardStats] Enable it in the config of this plugin: compatibilityMode
[15:42:12] [Server thread/WARN]: [ScoreboardStats] Couldn't register default listener: {0}
java.lang.IllegalArgumentException: Invalid format: 2.8.7Beta
	at com.github.games647.scoreboardstats.Version.parse(Version.java:89) ~[ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.Version.compare(Version.java:67) ~[ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.variables.defaults.FactionsVariables.<init>(FactionsVariables.java:31) ~[ScoreboardStats.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_73]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_73]
	at com.github.games647.scoreboardstats.variables.PluginListener.createInstance(PluginListener.java:149) ~[ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.variables.PluginListener.registerDefault(PluginListener.java:101) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.variables.PluginListener.addDefaultReplacers(PluginListener.java:133) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.<init>(ReplaceManager.java:41) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.SbManager.<init>(SbManager.java:27) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.<init>(BukkitScoreboardManager.java:38) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.ScoreboardStats.onEnable(ScoreboardStats.java:154) [ScoreboardStats.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]`

**Comment by games647** [comment]
I'm sorry, I completely misunderstood that.

**Comment by ireeskenz** [comment]
No problem, but i am only player to have this?

**Comment by games647** [comment]
The issue comes from Factions. It uses 2.8.7Beta as a version. The version checker failed, because in normal cases it's a convention that you write 2.8.7-Beta instead. I'll fix it now.

**Comment by ireeskenz** [comment]
Ok, thank you very much ! :D

**Comment by games647** [comment]
http://dev.bukkit.org/bukkit-plugins/scoreboardstats/files/45-scoreboard-stats-v0-9-8/

This file isn't approved by the Bukkit staff yet, so can't find it on the main page.

**Comment by ireeskenz** [comment]
Oh yeaaah ! Thank's you very much that's work ! You are a genious :D
