### ISSUE TITLE
Thirst and Disease Compatability

### ISSUE THREAD

**Issue by Tikkle** [games647/ScoreboardStats#85]
Nothing is misspelled.

`[17:52:18] [Server thread/WARN]: [ScoreboardStats] Replacer occurred an error: com.github.games647.scoreboardstats.variables.defaults.VaultVariables@22a381da[economy=net.milkbowl.vault.economy.plugins.Economy_Gringotts@2533ddf2,chat=net.milkbowl.vault.chat.plugins.Chat_PermissionsEx@64628d72,plugin=Vault v1.5.6-b49,async=false,global=false,constant=false,description=&cNo description,variables={money,playerInfo_*},enabled=false] for Tikkle So it will be removed to prevent future errors
java.lang.NoSuchFieldError: accountHolderFactory
	at net.milkbowl.vault.economy.plugins.Economy_Gringotts.getBalance(Economy_Gringotts.java:135) ~[Vault.jar:?]
	at net.milkbowl.vault.economy.plugins.Economy_Gringotts.getBalance(Economy_Gringotts.java:249) ~[Vault.jar:?]
	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:25) ~[Vault.jar:?]
	at com.github.games647.scoreboardstats.variables.defaults.VaultVariables.onReplace(VaultVariables.java:55) ~[ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:199) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.createScoreboard(BukkitScoreboardManager.java:76) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.onUpdate(BukkitScoreboardManager.java:109) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:54) [ScoreboardStats.jar:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[17:52:18] [Server thread/INFO]: [ScoreboardStats] Cannot find variable with name: (VariableItem{textVariable=false, variable=thirst, displayText=§9Hydration, score=0}) Maybe you misspelled it or the replacer isnt available yet
[17:52:18] [Server thread/INFO]: [ScoreboardStats] Cannot find variable with name: (VariableItem{textVariable=false, variable=temp, displayText=§cTemperature, score=0}) Maybe you misspelled it or the replacer isnt available yet
[17:52:18] [Server thread/INFO]: [ScoreboardStats] Cannot find variable with name: (VariableItem{textVariable=false, variable=sick, displayText=§2Sickness, score=0}) Maybe you misspelled it or the replacer isnt available yet
[17:52:23] [Server thread/WARN]: [ScoreboardStats] Replacer occurred an error: com.github.games647.scoreboardstats.variables.defaults.VaultVariables@22a381da[economy=net.milkbowl.vault.economy.plugins.Economy_Gringotts@2533ddf2,chat=net.milkbowl.vault.chat.plugins.Chat_PermissionsEx@64628d72,plugin=Vault v1.5.6-b49,async=false,global=false,constant=false,description=&cNo description,variables={money,playerInfo_*},enabled=false] for Tikkle So it will be removed to prevent future errors
java.lang.NoSuchFieldError: accountHolderFactory
	at net.milkbowl.vault.economy.plugins.Economy_Gringotts.getBalance(Economy_Gringotts.java:135) ~[Vault.jar:?]
	at net.milkbowl.vault.economy.plugins.Economy_Gringotts.getBalance(Economy_Gringotts.java:249) ~[Vault.jar:?]
	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:25) ~[Vault.jar:?]
	at com.github.games647.scoreboardstats.variables.defaults.VaultVariables.onReplace(VaultVariables.java:55) ~[ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.getScoreLegacy(ReplaceManager.java:250) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.variables.ReplaceManager.getScore(ReplaceManager.java:196) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.sendUpdate(BukkitScoreboardManager.java:169) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.scoreboard.bukkit.BukkitScoreboardManager.onUpdate(BukkitScoreboardManager.java:111) [ScoreboardStats.jar:?]
	at com.github.games647.scoreboardstats.RefreshTask.run(RefreshTask.java:54) [ScoreboardStats.jar:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9_Mar24-2016.jar:git-Spigot-90839e6-c5d27c5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[17:52:23] [Server thread/INFO]: [ScoreboardStats] Cannot find variable with name: (VariableItem{textVariable=false, variable=money, displayText=§aTime Coins, score=0}) Maybe you misspelled it or the replacer isnt available yet`

**Comment by games647** [comment]
For Thirst and Disease you have to activate scoreboardstats support in those plugins. The other error shows that Vault is not compatible with your Gringotts plugin. It needs to be updated.

**Comment by Tikkle** [comment]
it keeps saying unknown variables:


%sick%
%temp%


i have it enabled on disease!

**Comment by games647** [comment]
Do you reloaded the plugin?

**Comment by Tikkle** [comment]
no, i restart the server everytime i make a change

**Comment by games647** [comment]
It works for me using the latest uploaded version of ScoreboardStats and Thirst. Can you show me the config of both plugins?

**Comment by Tikkle** [comment]
[Configs.zip](https://github.com/games647/ScoreboardStats/files/192031/Configs.zip)

**Comment by games647** [comment]
Could you also send me your startup log?

**Comment by Tikkle** [comment]
[latest.txt](https://github.com/games647/ScoreboardStats/files/193733/latest.txt)

**Comment by games647** [comment]
>java.lang.IllegalArgumentException: given itemstack is not a potion
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.9_Mar28-2016.jar:git-Spigot-2038f4a-15222c8]
	at org.bukkit.potion.Potion.apply(Potion.java:143) ~[spigot-1.9_Mar28-2016.jar:git-Spigot-2038f4a-15222c8]
	at com.hmmcrunchy.disease.ItemFactory.createDiseaseVial(ItemFactory.java:146) ~[?:?]
	at com.hmmcrunchy.disease.Disease.onEnable(Disease.java:576) ~[?:?]

The plugin errors before it could hook into ScoreboardStats. Because of this error the initialization of the plugin aborts. Please report the error to the author of Disease. If this error is fixed, the plugin will work perfectly fine with ScoreboardStats.
